#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                any { image 'maven:3.8.5-jdk-11' }
            }
        steps {
            sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}
